//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMC2016.Models.Tools
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public int DepID { get; set; }
        public string DepEN { get; set; }
        public string DepTH { get; set; }
    }
}
