//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMC2016.Models.Tools
{
    using System.ComponentModel.DataAnnotations;    
    public partial class Login
    {
        public int UserID { get; set; }

        [Required]
        public string Username { get; set; }

        [DataType(DataType.Password)]
        public string Password { get; set; }
        public int DepID { get; set; }
        public int PerID { get; set; }
        public bool IsLock { get; set; }
    }
}
