//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMC2016.Models.Tools
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuBarItem
    {
        public int MenuID { get; set; }
        public string MenuNameOption { get; set; }
        public string MenuController { get; set; }
        public string MenuAction { get; set; }
        public string MenuImage { get; set; }
        public Nullable<int> MenuDep { get; set; }
        public bool MenuStatus { get; set; }
        public Nullable<bool> MenuIsParrent { get; set; }
        public int MenuParrentID { get; set; }
    }
}
