//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMC2016.Models.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERMAINTENANCE
    {
        public bool isdelete { get; set; }
        public Nullable<int> status { get; set; }
        public bool isPM { get; set; }
        public int pmmasterline { get; set; }
        public int pmschline { get; set; }
        public Nullable<System.DateTime> pmAppointDate { get; set; }
        public int orderTypeid { get; set; }
        public int actionpiority { get; set; }
        public Nullable<System.DateTime> orderdate { get; set; }
        public int orderid { get; set; }
        public string orderCode { get; set; }
        public string s_order { get; set; }
        public int yearservice { get; set; }
        public int ordercountno { get; set; }
        public string or_date { get; set; }
        public int custid { get; set; }
        public string acccustcode { get; set; }
        public string cus_na { get; set; }
        public string productid { get; set; }
        public string type { get; set; }
        public string s_no { get; set; }
        public string errorcode { get; set; }
        public string error { get; set; }
        public string month { get; set; }
        public int period { get; set; }
        public int fiscyear { get; set; }
        public Nullable<System.DateTime> year { get; set; }
        public int duedate { get; set; }
        public Nullable<System.DateTime> finishdate { get; set; }
        public bool inWarrantyService { get; set; }
        public decimal servicecost { get; set; }
        public decimal sparepartcost { get; set; }
        public string audituser { get; set; }
        public Nullable<System.DateTime> auditdt { get; set; }
        public string modiuser { get; set; }
        public Nullable<System.DateTime> modidt { get; set; }
    }
}
